# nginx_setup/handlers/main.yml
---
- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: stop nginx
  service:
    name: nginx
    state: stopped
