# deploy_tomcat/tasks/main.yml
---
# roles/deploy_tomcat/tasks/main.yml
- name: Ensure Java is installed
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes

- name: Ensure Tomcat directory exists
  file:
    path: "{{ tomcat_install_dir }}"
    state: directory

- name: Ensure Tomcat directory ownership is correct
  file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat
    recurse: yes

- name: Download Tomcat
  get_url:
    url: "{{ tomcat_url }}"
    dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"

- name: Extract Tomcat
  unarchive:
    src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_install_dir }}"
    remote_src: yes

- name: Ensure webapps directory exists
  file:
    path: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/webapps"
    state: directory
    owner: tomcat
    group: tomcat

- name: Deploy helloworld.war
  copy:
    src: "{{ role_path }}/files/{{ helloworld_war }}"
    dest: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/webapps/{{ helloworld_war }}"
    owner: tomcat
    group: tomcat
    mode: '0644'

- name: Change Tomcat port to {{ tomcat_port }}
  lineinfile:
    path: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/conf/server.xml"
    regexp: '(<Connector port=")[0-9]+(")'
    line: '\1{{ tomcat_port }}\2'
    state: present
  notify: restart tomcat

# - name: Create setenv.sh to set JAVA_HOME
#   copy:
#     dest: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/bin/setenv.sh"
#     content: |
#       #!/bin/sh
#       export JAVA_HOME={{ java_home }}
#     mode: '0755'

# - name: Ensure setenv.sh exists and has correct permissions
#   copy:
#     dest: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/bin/setenv.sh"
#     content: |
#       #!/bin/sh
#       export JAVA_HOME={{ java_home }}
#       export CATALINA_HOME={{ tomcat_install_dir }}
#       export PATH=$JAVA_HOME/bin:$PATH
#     mode: '0755'
#   notify:
#     - Restart Tomcat

- name: Create systemd service file for Tomcat
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  notify:
    - Reload systemd
    - Restart Tomcat

- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: yes

# tasks/main.yml
- name: Set JAVA_HOME in .bashrc
  lineinfile:
    path: "/home/ubuntu/.bashrc"
    regexp: '^export JAVA_HOME='
    line: 'export JAVA_HOME="{{ java_home }}"'
    state: present

- name: Update PATH in .bashrc
  lineinfile:
    path: "/home/ubuntu/.bashrc"
    regexp: '^export PATH=.*'
    line: 'export PATH=$JAVA_HOME/bin:$PATH'
    state: present

- name: Set CATALINA_HOME in .bashrc
  lineinfile:
    path: "/home/ubuntu/.bashrc"
    regexp: '^export CATALINA_HOME='
    line: 'export CATALINA_HOME="{{ tomcat_install_dir }}"'
    state: present

- name: Source .bashrc to apply changes (for current session only)
  shell: source ~/.bashrc
  args:
    executable: /bin/bash
  register: source_result

- name: Ensure Tomcat is enabled and started
  systemd:
    name: tomcat
    enabled: yes
    state: started
  become: yes

